[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#fec2d4"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "warning"

[client.showRunOnSave]
enabled = false
